<?php 
require_once("db_methods.php");
require_once("db.php");
require_once("cf.php");
require_once("dept.php");
require_once("dept_payment.php");
require_once("college_payment.php");
require_once("admin.php");
require_once("school.php");
require_once("session.php");
require_once("function.php");
?>
